(()=>{
'use strict';
const C=window.CR20KBSnapFitHolder,$=id=>document.getElementById(id);
if(!C)return;
const NORMAL_RATIO=22/22.03;
const PRESETS=Object.freeze({loose:{ratio:1.005},normal:{ratio:NORMAL_RATIO},firm:{ratio:.995},tight:{ratio:.990}});
const QUALITY=Object.freeze({draft:{quality:24,arcChord:.35},normal:{quality:48,arcChord:.18},fine:{quality:80,arcChord:.10}});
const T={
ru:{title:'Держатель-защёлка → STL',lead:'Измерьте наружный диаметр цилиндра. Базовая посадка проверена реальной печатью на PETG HF; STL строится локально в браузере.',back:'← Починить',settings:'Быстрые настройки',D:'Наружный Ø предмета D, мм',width:'Ширина кронштейна по оси, мм',widthHint:'Для D ≥ 20 мм стандартная ширина — 20 мм. Если нагрузка требует больше — увеличьте вручную; для длинных предметов обычно лучше несколько кронштейнов.',advanced:'Развёрнутые настройки',fit:'Посадка',loose:'Свободно',normal:'Нормально · проверено',firm:'Плотно',tight:'Туго',fitExact:'Точная поправка Δ, мм',fitHint:'«Нормально» воспроизводит физически проверенный образец: Ø22,03 мм → внутренний Ø22,00 мм. Остальные пресеты и другие диаметры пока экспериментальные.',L:'L до оси цилиндра, мм',LHint:'L не масштабируется вместе с диаметром. База — 41 мм; если крупное кольцо физически не помещается, минимальный L увеличится автоматически.',wallInput:'Толщина стенки защёлки, мм',wallHint:'База — 2,5 мм. Для другого диаметра это отдельный параметр, а не автоматический масштаб.',hole:'Отверстие под винт Ø, мм',holeHint:'После реального монтажа: для D ≥ 20 мм стандарт Ø6,5 мм, для меньших диаметров Ø5 мм. Можно изменить вручную.',quality:'Качество STL',draft:'Черновик',qualityNormal:'Обычно',fine:'Точно',clip:'Внутренний Ø',wall:'Стенка',axis:'L до оси',plate:'Планка',pitch:'Межосевое',depthOut:'Ширина',download:'Скачать STL',reset:'Сбросить',preview3d:'3D · тяните мышью/пальцем для вращения',previewTop:'Вид сверху · L показан до оси цилиндра',view3d:'3D',viewTop:'Вид сверху',validated:'БАЗОВАЯ ПОСАДКА ПРОВЕРЕНА',validationCopy:'PETG HF · предмет Ø22,03 мм · 22 мм ширина · нормальное усилие защёлкивания и удержания.',large:'Для Ø60–100 мм разумнее использовать 2–3 отдельных кронштейна по длине предмета, а не один чрезмерно широкий.',LAdjusted:'Для выбранного диаметра L автоматически увеличен до физически допустимого минимума.',status:'Готово. Размеры остаются в браузере.',source:'Исходники',inspired:'Идея / исходный ролик',experiment:'TEST: нормальная посадка подтверждена только на Ø22,03 мм и PETG HF. Для другого материала/диаметра сначала распечатайте один образец.'},
en:{title:'Snap-Fit Holder → STL',lead:'Measure the cylinder outside diameter. The baseline fit was validated by a real PETG HF print; STL is generated locally in your browser.',back:'← Repair',settings:'Quick settings',D:'Object outside Ø D, mm',width:'Holder width along axis, mm',widthHint:'For D ≥ 20 mm the standard width is 20 mm. Increase it manually when the load requires more; long objects are usually better supported by multiple holders.',advanced:'Advanced settings',fit:'Fit',loose:'Loose',normal:'Normal · validated',firm:'Firm',tight:'Tight',fitExact:'Exact diametral offset Δ, mm',fitHint:'Normal reproduces the physically tested sample: 22.03 mm object → 22.00 mm clip ID. Other presets and diameters are experimental.',L:'L to cylinder axis, mm',LHint:'L no longer scales with diameter. Baseline is 41 mm; if a large ring cannot physically fit, the minimum L is raised automatically.',wallInput:'Snap wall thickness, mm',wallHint:'Baseline is 2.5 mm. For other diameters this is independent, not automatically scaled.',hole:'Screw hole Ø, mm',holeHint:'After a real mounting test: D ≥ 20 mm defaults to Ø6.5 mm; smaller diameters default to Ø5 mm. You can override it manually.',quality:'STL quality',draft:'Draft',qualityNormal:'Normal',fine:'Fine',clip:'Inside Ø',wall:'Wall',axis:'L to axis',plate:'Mount plate',pitch:'Hole pitch',depthOut:'Width',download:'Download STL',reset:'Reset',preview3d:'3D · drag with mouse/finger to rotate',previewTop:'Top view · L is dimensioned to cylinder axis',view3d:'3D',viewTop:'Top view',validated:'BASELINE FIT VALIDATED',validationCopy:'PETG HF · 22.03 mm cylinder · 22 mm width · good snap-in and holding force.',large:'For Ø60–100 mm, use 2–3 separate holders along the object instead of one excessively wide holder.',LAdjusted:'For this diameter L was automatically raised to the physical minimum.',status:'Ready. Dimensions stay in your browser.',source:'Source code',inspired:'Idea / source video',experiment:'TEST: the normal fit is physically validated only at Ø22.03 mm in PETG HF. Print one sample first for another material or diameter.'}}
let lang=new URLSearchParams(location.search).get('lang')==='en'?'en':'ru',preset='normal',autoWidth=true,autoHole=true,viewMode='3d';
let yaw=-.72,pitch=-.48,zoom=1,drag=null,meshCache=null,meshKey='',raf=0;
function presetFit(D,name=preset){return D*(PRESETS[name]?.ratio??PRESETS.normal.ratio)-D}
function defaultWidth(D){return Math.min(Math.max(D,12),20)}
function defaultHole(D){return C.defaultHoleD?C.defaultHoleD(D):(D>=20?6.5:5)}
function fmt(v,n=2){return Number(v).toFixed(n)}
function read(){const D=+$('D').value,fit=+$('fit').value,clipD=Math.max(8,D+fit),width=+$('width').value,q=QUALITY[$('quality').value]||QUALITY.normal;return{D,fit,width,depthRatio:width/clipD,holeD:Math.min(+$('holeD').value,Math.max(3,width-1)),L:+$('L').value,wall:+$('wall').value,quality:q.quality,arcChord:q.arcChord}}
function setCopy(){document.querySelectorAll('[data-t]').forEach(el=>{const k=el.dataset.t;if(T[lang][k])el.textContent=T[lang][k]});document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.documentElement.lang=lang;updatePreviewLabel()}
function setPreset(name){preset=name;const D=+$('D').value;$('fit').value=fmt(presetFit(D,name),3);document.querySelectorAll('[data-fit-preset]').forEach(b=>b.classList.toggle('active',b.dataset.fitPreset===name));invalidate()}
function setupCanvas(){const c=$('canvas'),rect=c.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1),W=Math.max(320,Math.round(rect.width*dpr)),H=Math.max(360,Math.round(rect.height*dpr));if(c.width!==W||c.height!==H){c.width=W;c.height=H}const ctx=c.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);return{c,ctx,w:W/dpr,h:H/dpr}}
function drawDimension(ctx,x1,y1,x2,y2,label){ctx.save();ctx.strokeStyle='#397797';ctx.fillStyle='#397797';ctx.lineWidth=1.4;ctx.beginPath();ctx.moveTo(x1,y1);ctx.lineTo(x2,y2);ctx.stroke();const s=6;for(const [x,dir] of [[x1,1],[x2,-1]]){ctx.beginPath();ctx.moveTo(x,y1);ctx.lineTo(x+dir*s,y1-s*.55);ctx.moveTo(x,y1);ctx.lineTo(x+dir*s,y1+s*.55);ctx.stroke()}ctx.font='800 11px system-ui';ctx.textAlign='center';ctx.textBaseline='bottom';ctx.fillText(label,(x1+x2)/2,y1-5);ctx.restore()}
function drawTop(r){const{ctx,w,h}=setupCanvas();ctx.clearRect(0,0,w,h);const b=r.bounds2d,s=Math.min((w-80)/(b.xmax-b.xmin),(h-120)/(b.ymax-b.ymin)),ox=40-b.xmin*s,oy=(h-38)/2+(b.ymin+b.ymax)*s/2,P=q=>[ox+q[0]*s,oy-q[1]*s];ctx.beginPath();r.points.forEach((q,i)=>{const[x,y]=P(q);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fillStyle='#e9efe7';ctx.strokeStyle='#6d7d70';ctx.lineWidth=1.6;ctx.fill();ctx.stroke();ctx.strokeStyle='#b56b50';ctx.lineWidth=1.3;for(const sy of[-r.holeY,r.holeY]){const[x,y]=P([r.plateThickness/2,sy]);ctx.beginPath();ctx.arc(x,y,r.params.holeD/2*s,0,Math.PI*2);ctx.stroke()}ctx.setLineDash([5,5]);ctx.strokeStyle='#7b8790';const[cx,cy]=P([r.ringCenterX,0]);ctx.beginPath();ctx.arc(cx,cy,r.innerDiameter/2*s,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#536158';ctx.font='700 11px system-ui';ctx.textAlign='center';ctx.fillText(`Ø${fmt(r.innerDiameter,2)}`,cx,cy+4);const p0=P([0,0]),pc=P([r.ringCenterX,0]),yd=h-24;ctx.strokeStyle='rgba(57,119,151,.45)';ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(p0[0],p0[1]);ctx.lineTo(p0[0],yd);ctx.moveTo(pc[0],pc[1]);ctx.lineTo(pc[0],yd);ctx.stroke();drawDimension(ctx,p0[0],yd,pc[0],yd,`L = ${fmt(r.ringCenterX,1)} mm`)}
function previewMesh(opts){const key=[opts.D,opts.fit,opts.width,opts.holeD,opts.L,opts.wall].map(v=>Number(v).toFixed(4)).join('|');if(key!==meshKey){meshKey=key;meshCache=C.mesh({...opts,quality:24,arcChord:.5})}return meshCache}
function transformed(p,cx,cy){let x=p[0]-cx,y=p[1]-cy,z=p[2];const cz=Math.cos(yaw),sz=Math.sin(yaw),x1=cz*x-sz*y,y1=sz*x+cz*y;const cp=Math.cos(pitch),sp=Math.sin(pitch),y2=cp*y1-sp*z,z2=sp*y1+cp*z;return[x1,y2,z2]}
function draw3D(r,opts){const{ctx,w,h}=setupCanvas();ctx.clearRect(0,0,w,h);const M=previewMesh(opts),cx=(r.bounds2d.xmin+r.bounds2d.xmax)/2,cy=(r.bounds2d.ymin+r.bounds2d.ymax)/2,extent=Math.max(r.overall.x,r.overall.y,r.overall.z),scale=Math.min(w,h)/(extent*1.65)*zoom,faces=[];for(const f of M.faces){const q=f.map(p=>transformed(p,cx,cy)),depth=(q[0][2]+q[1][2]+q[2][2])/3;const ux=q[1][0]-q[0][0],uy=q[1][1]-q[0][1],uz=q[1][2]-q[0][2],vx=q[2][0]-q[0][0],vy=q[2][1]-q[0][1],vz=q[2][2]-q[0][2],nx=uy*vz-uz*vy,ny=uz*vx-ux*vz,nz=ux*vy-uy*vx,nl=Math.hypot(nx,ny,nz)||1,light=Math.max(-1,Math.min(1,(nx*.25-ny*.35+nz*.9)/nl));faces.push({q,depth,light})}faces.sort((a,b)=>a.depth-b.depth);for(const f of faces){const shade=Math.round(205+28*(f.light*.5+.5));ctx.beginPath();f.q.forEach((q,i)=>{const x=w/2+q[0]*scale,y=h/2-q[1]*scale;i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fillStyle=`rgb(${shade},${Math.min(246,shade+6)},${Math.max(180,shade-4)})`;ctx.strokeStyle='rgba(79,94,81,.28)';ctx.lineWidth=.55;ctx.fill();ctx.stroke()}ctx.fillStyle='rgba(50,65,54,.72)';ctx.font='700 10px system-ui';ctx.textAlign='right';ctx.fillText(lang==='ru'?'тяните для вращения · колесо для масштаба':'drag to rotate · wheel to zoom',w-14,h-14)}
function updateSummary(r){$('clipV').textContent=`${fmt(r.innerDiameter)} mm`;$('wallV').textContent=`${fmt(r.wall)} mm`;$('axisV').textContent=`${fmt(r.ringCenterX,1)} mm`;$('plateV').textContent=`${fmt(r.plateThickness)} × ${fmt(r.flangeWidth)} mm`;$('pitchV').textContent=`${fmt(r.holeSpacing)} mm`;$('depthV').textContent=`${fmt(r.params.width)} mm`;$('largeNote').hidden=r.params.D<60;$('LAdjustedNote').hidden=!r.params.LAdjusted;$('status').textContent=T[lang].status}
function updatePreviewLabel(){const el=$('previewLabel');if(el)el.textContent=T[lang][viewMode==='3d'?'preview3d':'previewTop'];document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===viewMode))}
function draw(){const opts=read(),r=C.resolve(opts);if(r.params.LAdjusted&&Math.abs(+$('L').value-r.params.L)>.04)$('L').value=fmt(r.params.L,1);updateSummary(r);updatePreviewLabel();viewMode==='3d'?draw3D(r,{...opts,L:r.params.L}):drawTop(r)}
function invalidate(rebuild=true){if(rebuild){meshKey='';meshCache=null}if(raf)return;raf=requestAnimationFrame(()=>{raf=0;draw()})}
function send(eventName){try{const ep=window.CR20KB_ANALYTICS_ENDPOINT;if(ep&&navigator.sendBeacon)navigator.sendBeacon(ep,new Blob([JSON.stringify({event:eventName,nodeId:'snap-fit-holder',preset,language:lang,path:location.pathname,at:new Date().toISOString()})],{type:'application/json'}))}catch(_){}}
async function download(){const btn=$('download'),st=$('status');btn.disabled=true;st.textContent=lang==='ru'?'Строю STL…':'Building STL…';await new Promise(r=>setTimeout(r,20));try{const s=C.binaryStl(read()),blob=new Blob([s.buffer],{type:'model/stl'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=s.fileName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);send('product_export');st.textContent=(lang==='ru'?'Готово: ':'Done: ')+`${s.mesh.triangles.toLocaleString()} triangles`}catch(e){st.textContent=(lang==='ru'?'Ошибка: ':'Error: ')+e.message}finally{btn.disabled=false}}
$('D').addEventListener('input',()=>{const D=+$('D').value;if(preset!=='custom')$('fit').value=fmt(presetFit(D,preset),3);if(autoWidth)$('width').value=fmt(defaultWidth(D),1);if(autoHole)$('holeD').value=fmt(defaultHole(D),1);invalidate()});
$('width').addEventListener('input',()=>{autoWidth=false;const maxHole=Math.max(3,+$('width').value-1);if(+$('holeD').value>maxHole)$('holeD').value=fmt(maxHole,1);invalidate()});
$('fit').addEventListener('input',()=>{preset='custom';document.querySelectorAll('[data-fit-preset]').forEach(b=>b.classList.remove('active'));invalidate()});
$('holeD').addEventListener('input',()=>{autoHole=false;invalidate()});
['quality','L','wall'].forEach(id=>$(id).addEventListener('input',invalidate));
document.querySelectorAll('[data-fit-preset]').forEach(b=>b.addEventListener('click',()=>setPreset(b.dataset.fitPreset)));
document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;setCopy();invalidate(false)}));
document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{viewMode=b.dataset.view;updatePreviewLabel();invalidate(false)}));
$('reset').addEventListener('click',()=>{preset='normal';autoWidth=true;autoHole=true;$('D').value='22.03';$('width').value=fmt(defaultWidth(22.03),1);$('holeD').value=fmt(defaultHole(22.03),1);$('quality').value='normal';$('L').value='41';$('wall').value='2.5';setPreset('normal')});
$('download').addEventListener('click',download);
const canvas=$('canvas');
canvas.addEventListener('pointerdown',e=>{if(viewMode!=='3d')return;drag={x:e.clientX,y:e.clientY};canvas.setPointerCapture?.(e.pointerId)});
canvas.addEventListener('pointermove',e=>{if(!drag||viewMode!=='3d')return;yaw+=(e.clientX-drag.x)*.009;pitch=Math.max(-1.35,Math.min(1.35,pitch+(e.clientY-drag.y)*.009));drag={x:e.clientX,y:e.clientY};invalidate(false)});
canvas.addEventListener('pointerup',()=>{drag=null});canvas.addEventListener('pointercancel',()=>{drag=null});
canvas.addEventListener('wheel',e=>{if(viewMode!=='3d')return;e.preventDefault();zoom=Math.max(.55,Math.min(2.4,zoom*Math.exp(-e.deltaY*.001)));invalidate(false)},{passive:false});
window.addEventListener('resize',()=>invalidate(false));
setCopy();$('width').value=fmt(defaultWidth(+$('D').value),1);$('holeD').value=fmt(defaultHole(+$('D').value),1);setPreset('normal');send('page_view');
})();