(()=>{
'use strict';
const C=window.CR20KBSnapFitHolder,$=id=>document.getElementById(id);
if(!C)return;
const NORMAL_RATIO=22/22.03;
const PRESETS=Object.freeze({loose:{ratio:1.005},normal:{ratio:NORMAL_RATIO},firm:{ratio:.995},tight:{ratio:.990}});
const QUALITY=Object.freeze({draft:{quality:24,arcChord:.35},normal:{quality:48,arcChord:.18},fine:{quality:80,arcChord:.10}});
const T={
ru:{title:'Держатель-защёлка → STL',lead:'Измерьте наружный диаметр цилиндра. Базовая посадка проверена реальной печатью на PETG HF; STL строится локально в браузере.',back:'← Починить',settings:'Быстрые настройки',D:'Наружный Ø предмета D, мм',width:'Ширина кронштейна по оси, мм',widthHint:'Для больших и длинных предметов обычно лучше 2–3 кронштейна, чем один очень широкий.',advanced:'Развёрнутые настройки',fit:'Посадка',loose:'Свободно',normal:'Нормально · проверено',firm:'Плотно',tight:'Туго',fitExact:'Точная поправка Δ, мм',fitHint:'«Нормально» воспроизводит физически проверенный образец: Ø22,03 мм → внутренний Ø22,00 мм. Остальные пресеты и другие диаметры пока экспериментальные.',hole:'Отверстие под винт Ø, мм',quality:'Качество STL',draft:'Черновик',qualityNormal:'Обычно',fine:'Точно',clip:'Внутренний Ø',wall:'Стенка',plate:'Планка',pitch:'Межосевое',stem:'Шейка',depthOut:'Ширина',download:'Скачать STL',reset:'Сбросить',preview:'Вид сверху · физически проверенный профиль',validated:'БАЗОВАЯ ПОСАДКА ПРОВЕРЕНА',validationCopy:'PETG HF · предмет Ø22,03 мм · 22 мм ширина · нормальное усилие защёлкивания и удержания.',large:'Для Ø60–100 мм разумнее использовать 2–3 отдельных кронштейна по длине предмета, а не один чрезмерно широкий.',status:'Готово. Размеры остаются в браузере.',source:'Исходники',inspired:'Идея / исходный ролик',experiment:'TEST: нормальная посадка подтверждена только на Ø22,03 мм и PETG HF. Для другого материала/диаметра сначала распечатайте один образец.'},
en:{title:'Snap-Fit Holder → STL',lead:'Measure the cylinder outside diameter. The baseline fit was validated by a real PETG HF print; STL is generated locally in your browser.',back:'← Repair',settings:'Quick settings',D:'Object outside Ø D, mm',width:'Holder width along axis, mm',widthHint:'For large or long objects, 2–3 separate holders are usually better than one very wide holder.',advanced:'Advanced settings',fit:'Fit',loose:'Loose',normal:'Normal · validated',firm:'Firm',tight:'Tight',fitExact:'Exact diametral offset Δ, mm',fitHint:'Normal reproduces the physically tested sample: 22.03 mm object → 22.00 mm clip ID. Other presets and diameters are experimental.',hole:'Screw hole Ø, mm',quality:'STL quality',draft:'Draft',qualityNormal:'Normal',fine:'Fine',clip:'Inside Ø',wall:'Wall',plate:'Mount plate',pitch:'Hole pitch',stem:'Stem',depthOut:'Width',download:'Download STL',reset:'Reset',preview:'Top view · physically tested profile',validated:'BASELINE FIT VALIDATED',validationCopy:'PETG HF · 22.03 mm cylinder · 22 mm width · good snap-in and holding force.',large:'For Ø60–100 mm, use 2–3 separate holders along the object instead of one excessively wide holder.',status:'Ready. Dimensions stay in your browser.',source:'Source code',inspired:'Idea / source video',experiment:'TEST: the normal fit is physically validated only at Ø22.03 mm in PETG HF. Print one sample first for another material or diameter.'}}
let lang=new URLSearchParams(location.search).get('lang')==='en'?'en':'ru',preset='normal',autoWidth=true;
function presetFit(D,name=preset){return D*(PRESETS[name]?.ratio??PRESETS.normal.ratio)-D}
function defaultWidth(D){return Math.min(Math.max(D,12),30)}
function fmt(v,n=2){return Number(v).toFixed(n)}
function read(){const D=+$('D').value,fit=+$('fit').value,clipD=Math.max(8,D+fit),width=+$('width').value,q=QUALITY[$('quality').value]||QUALITY.normal;return{D,fit,width,depthRatio:width/clipD,holeD:Math.min(+$('holeD').value,Math.max(3,width-1)),quality:q.quality,arcChord:q.arcChord}}
function setCopy(){document.querySelectorAll('[data-t]').forEach(el=>{const k=el.dataset.t;if(T[lang][k])el.textContent=T[lang][k]});document.querySelectorAll('[data-lang]').forEach(b=>b.classList.toggle('active',b.dataset.lang===lang));document.documentElement.lang=lang}
function setPreset(name){preset=name;const D=+$('D').value;$('fit').value=fmt(presetFit(D,name),3);document.querySelectorAll('[data-fit-preset]').forEach(b=>b.classList.toggle('active',b.dataset.fitPreset===name));draw()}
function draw(){const r=C.resolve(read()),c=$('canvas'),ctx=c.getContext('2d'),rect=c.getBoundingClientRect(),dpr=Math.min(2,devicePixelRatio||1),W=Math.max(320,Math.round(rect.width*dpr)),H=Math.max(380,Math.round(rect.height*dpr));if(c.width!==W||c.height!==H){c.width=W;c.height=H}ctx.setTransform(dpr,0,0,dpr,0,0);const w=W/dpr,h=H/dpr;ctx.clearRect(0,0,w,h);const b=r.bounds2d,s=Math.min((w-70)/(b.xmax-b.xmin),(h-90)/(b.ymax-b.ymin)),ox=35-b.xmin*s,oy=h/2+(b.ymin+b.ymax)*s/2,P=q=>[ox+q[0]*s,oy-q[1]*s];ctx.beginPath();r.points.forEach((q,i)=>{const[x,y]=P(q);i?ctx.lineTo(x,y):ctx.moveTo(x,y)});ctx.closePath();ctx.fillStyle='#e9efe7';ctx.strokeStyle='#6d7d70';ctx.lineWidth=1.6;ctx.fill();ctx.stroke();ctx.strokeStyle='#b56b50';ctx.lineWidth=1.3;for(const sy of[-r.holeY,r.holeY]){const[x,y]=P([r.plateThickness/2,sy]);ctx.beginPath();ctx.arc(x,y,r.params.holeD/2*s,0,Math.PI*2);ctx.stroke()}ctx.setLineDash([5,5]);ctx.strokeStyle='#7b8790';const[cx,cy]=P([r.ringCenterX,0]);ctx.beginPath();ctx.arc(cx,cy,r.innerDiameter/2*s,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='#536158';ctx.font='700 11px system-ui';ctx.textAlign='center';ctx.fillText(`Ø${fmt(r.innerDiameter,2)}`,cx,cy+4);$('clipV').textContent=`${fmt(r.innerDiameter)} mm`;$('wallV').textContent=`${fmt(r.wall)} mm`;$('plateV').textContent=`${fmt(r.plateThickness)} × ${fmt(r.flangeWidth)} mm`;$('pitchV').textContent=`${fmt(r.holeSpacing)} mm`;$('stemV').textContent=`${fmt(r.stemWidth)} mm`;$('depthV').textContent=`${fmt(r.params.width)} mm`;$('largeNote').hidden=r.params.D<60;$('status').textContent=T[lang].status}
function send(eventName){try{const ep=window.CR20KB_ANALYTICS_ENDPOINT;if(ep&&navigator.sendBeacon)navigator.sendBeacon(ep,new Blob([JSON.stringify({event:eventName,nodeId:'snap-fit-holder',preset,language:lang,path:location.pathname,at:new Date().toISOString()})],{type:'application/json'}))}catch(_){}}
async function download(){const btn=$('download'),st=$('status');btn.disabled=true;st.textContent=lang==='ru'?'Строю STL…':'Building STL…';await new Promise(r=>setTimeout(r,20));try{const s=C.binaryStl(read()),blob=new Blob([s.buffer],{type:'model/stl'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=s.fileName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);send('product_export');st.textContent=(lang==='ru'?'Готово: ':'Done: ')+`${s.mesh.triangles.toLocaleString()} triangles`}catch(e){st.textContent=(lang==='ru'?'Ошибка: ':'Error: ')+e.message}finally{btn.disabled=false}}
$('D').addEventListener('input',()=>{const D=+$('D').value;if(preset!=='custom')$('fit').value=fmt(presetFit(D,preset),3);if(autoWidth)$('width').value=fmt(defaultWidth(D),1);draw()});$('width').addEventListener('input',()=>{autoWidth=false;const maxHole=Math.max(3,+$('width').value-1);if(+$('holeD').value>maxHole)$('holeD').value=fmt(maxHole,1);draw()});$('fit').addEventListener('input',()=>{preset='custom';document.querySelectorAll('[data-fit-preset]').forEach(b=>b.classList.remove('active'));draw()});['holeD','quality'].forEach(id=>$(id).addEventListener('input',draw));document.querySelectorAll('[data-fit-preset]').forEach(b=>b.addEventListener('click',()=>setPreset(b.dataset.fitPreset)));document.querySelectorAll('[data-lang]').forEach(b=>b.addEventListener('click',()=>{lang=b.dataset.lang;setCopy();draw()}));$('reset').addEventListener('click',()=>{preset='normal';autoWidth=true;$('D').value='22.03';$('width').value='22.0';$('holeD').value='5';$('quality').value='normal';setPreset('normal')});$('download').addEventListener('click',download);window.addEventListener('resize',draw);setCopy();$('width').value=fmt(defaultWidth(+$('D').value),1);setPreset('normal');send('page_view');
})();
